// demos/interaction-benchmark/apps/qwik/src/routes/index.tsx
import type { DocumentHead } from "@qwik.dev/router";
import { $, component$, sync$, useComputed$, useSignal } from "@qwik.dev/core";
import {
  COUNTER_INITIAL,
  FILTER_ITEMS,
  INITIAL_TAB,
  OVERVIEW_PROSE,
  ROUTES,
  STEPPER_INITIAL,
  STEPPER_MAX,
  STEPPER_MIN,
  TABS,
  documentTitle,
  filterCountText,
  filterItems,
  stepperDerivedText,
  toggleStatusText,
  type TabInfo,
} from "~/shared/data";

const CounterPanel = component$(() => {
  const count = useSignal(COUNTER_INITIAL);
  return (
    <section class="panel">
      <h3 class="panel-title">Counter</h3>
      <output class="value" data-testid="counter-value">
        {count.value}
      </output>
      <button
        type="button"
        class="button"
        data-testid="counter-increment"
        onClick$={() => count.value++}
      >
        Increment
      </button>
    </section>
  );
});

const TogglePanel = component$(() => {
  const on = useSignal(false);
  return (
    <section class="panel">
      <h3 class="panel-title">Toggle</h3>
      <button
        type="button"
        class="button"
        data-testid="toggle-button"
        aria-pressed={on.value ? "true" : "false"}
        onClick$={() => (on.value = !on.value)}
      >
        Notifications
      </button>
      <output class="value" data-testid="toggle-status">
        {toggleStatusText(on.value)}
      </output>
    </section>
  );
});

const StepperPanel = component$(() => {
  const value = useSignal(STEPPER_INITIAL);
  return (
    <section class="panel">
      <h3 class="panel-title">Stepper</h3>
      <div class="row">
        <button
          type="button"
          class="button"
          data-testid="stepper-decrement"
          aria-label="Decrease"
          disabled={value.value <= STEPPER_MIN}
          onClick$={() => {
            if (value.value > STEPPER_MIN) value.value--;
          }}
        >
          −
        </button>
        <output class="value" data-testid="stepper-value">
          {value.value}
        </output>
        <button
          type="button"
          class="button"
          data-testid="stepper-increment"
          aria-label="Increase"
          disabled={value.value >= STEPPER_MAX}
          onClick$={() => {
            if (value.value < STEPPER_MAX) value.value++;
          }}
        >
          +
        </button>
      </div>
      <p class="derived" data-testid="stepper-derived">
        {stepperDerivedText(value.value)}
      </p>
    </section>
  );
});

const TAB_KEYS = ["ArrowRight", "ArrowLeft", "Home", "End"];

const Tabs = component$(() => {
  const selected = useSignal<TabInfo["id"]>(INITIAL_TAB);
  const selectedTab = useComputed$(
    () => TABS.find((tab) => tab.id === selected.value) ?? TABS[0],
  );
  const moveFocus = $((key: string, index: number) => {
    let next: number;
    if (key === "ArrowRight") next = (index + 1) % TABS.length;
    else if (key === "ArrowLeft") next = (index - 1 + TABS.length) % TABS.length;
    else if (key === "Home") next = 0;
    else if (key === "End") next = TABS.length - 1;
    else return;
    const tab = TABS[next];
    selected.value = tab.id;
    document.getElementById(`tab-${tab.id}`)?.focus();
  });
  return (
    <div class="tabs">
      <div
        class="tablist"
        role="tablist"
        aria-label="Details"
        data-testid="overview-tabs"
      >
        {TABS.map((tab, index) => {
          const isSelected = selected.value === tab.id;
          return (
            <button
              key={tab.id}
              type="button"
              class="tab"
              role="tab"
              id={`tab-${tab.id}`}
              data-testid={`tab-${tab.id}`}
              aria-controls="tab-panel"
              aria-selected={isSelected ? "true" : "false"}
              tabIndex={isSelected ? 0 : -1}
              onClick$={() => (selected.value = tab.id)}
              onKeyDown$={[
                sync$((event: KeyboardEvent) => {
                  if (
                    ["ArrowRight", "ArrowLeft", "Home", "End"].includes(
                      event.key,
                    )
                  )
                    event.preventDefault();
                }),
                $((event: KeyboardEvent) => {
                  if (TAB_KEYS.includes(event.key))
                    return moveFocus(event.key, index);
                }),
              ]}
            >
              {tab.label}
            </button>
          );
        })}
      </div>
      <div
        class="tabpanel"
        role="tabpanel"
        id="tab-panel"
        data-testid="tab-panel"
        aria-labelledby={`tab-${selectedTab.value.id}`}
        tabIndex={0}
      >
        {selectedTab.value.content}
      </div>
    </div>
  );
});

const Filter = component$(() => {
  const query = useSignal("");
  const items = useComputed$(() => filterItems(FILTER_ITEMS, query.value));
  return (
    <section class="filter">
      <div class="field">
        <label class="field-label" for="filter-input">
          Filter items
        </label>
        <input
          class="input"
          type="search"
          id="filter-input"
          data-testid="filter-input"
          autoComplete="off"
          bind:value={query}
        />
      </div>
      <p class="muted" data-testid="filter-count">
        {filterCountText(items.value.length)}
      </p>
      {items.value.length === 0 ? (
        <p class="muted" data-testid="filter-empty">
          No matching items
        </p>
      ) : (
        <ul class="list" data-testid="filter-list">
          {items.value.map((item) => (
            <li key={item} data-testid="filter-item">
              {item}
            </li>
          ))}
        </ul>
      )}
    </section>
  );
});

export default component$(() => {
  return (
    <>
      <h1 class="page-title" data-testid="page-title">
        Overview
      </h1>
      <div class="prose">
        {OVERVIEW_PROSE.map((paragraph, index) => (
          <p key={index}>{paragraph}</p>
        ))}
      </div>
      <h2 class="section-title">Panels</h2>
      <div class="panels">
        <CounterPanel />
        <TogglePanel />
        <StepperPanel />
      </div>
      <Tabs />
      <Filter />
    </>
  );
});

export const head: DocumentHead = { title: documentTitle(ROUTES[0]) };

// demos/interaction-benchmark/apps/sveltekit/src/routes/+page.svelte
<script lang="ts">
	import {
		COUNTER_INITIAL,
		FILTER_ITEMS,
		INITIAL_TAB,
		OVERVIEW_PROSE,
		STEPPER_INITIAL,
		STEPPER_MAX,
		STEPPER_MIN,
		TABS,
		filterCountText,
		filterItems,
		stepperDerivedText,
		toggleStatusText
	} from '$lib/shared/data';

	let count = $state(COUNTER_INITIAL);
	let pressed = $state(false);
	let stepper = $state(STEPPER_INITIAL);
	let selectedTab = $state(INITIAL_TAB);
	let query = $state('');

	const selected = $derived(TABS.find((t) => t.id === selectedTab) ?? TABS[0]);
	const matches = $derived(filterItems(FILTER_ITEMS, query));
	const tabButtons: HTMLButtonElement[] = [];

	function onTabKeydown(event: KeyboardEvent, index: number) {
		let next: number;
		if (event.key === 'ArrowRight') next = (index + 1) % TABS.length;
		else if (event.key === 'ArrowLeft') next = (index - 1 + TABS.length) % TABS.length;
		else if (event.key === 'Home') next = 0;
		else if (event.key === 'End') next = TABS.length - 1;
		else return;
		event.preventDefault();
		selectedTab = TABS[next].id;
		tabButtons[next].focus();
	}
</script>

<div class="prose">
	{#each OVERVIEW_PROSE as paragraph, i (i)}
		<p>{paragraph}</p>
	{/each}
</div>

<h2 class="section-title">Panels</h2>
<div class="panels">
	<section class="panel">
		<h3 class="panel-title">Counter</h3>
		<output class="value" data-testid="counter-value">{count}</output>
		<button type="button" class="button" data-testid="counter-increment" onclick={() => count++}
			>Increment</button
		>
	</section>
	<section class="panel">
		<h3 class="panel-title">Toggle</h3>
		<button
			type="button"
			class="button"
			data-testid="toggle-button"
			aria-pressed={pressed ? 'true' : 'false'}
			onclick={() => (pressed = !pressed)}>Notifications</button
		>
		<output class="value" data-testid="toggle-status">{toggleStatusText(pressed)}</output>
	</section>
	<section class="panel">
		<h3 class="panel-title">Stepper</h3>
		<div class="row">
			<button
				type="button"
				class="button"
				data-testid="stepper-decrement"
				aria-label="Decrease"
				disabled={stepper <= STEPPER_MIN}
				onclick={() => (stepper = Math.max(STEPPER_MIN, stepper - 1))}>−</button
			>
			<output class="value" data-testid="stepper-value">{stepper}</output>
			<button
				type="button"
				class="button"
				data-testid="stepper-increment"
				aria-label="Increase"
				disabled={stepper >= STEPPER_MAX}
				onclick={() => (stepper = Math.min(STEPPER_MAX, stepper + 1))}>+</button
			>
		</div>
		<p class="derived" data-testid="stepper-derived">{stepperDerivedText(stepper)}</p>
	</section>
</div>

<div class="tabs">
	<div class="tablist" role="tablist" aria-label="Details" data-testid="overview-tabs">
		{#each TABS as tab, i (tab.id)}
			<button
				bind:this={tabButtons[i]}
				type="button"
				class="tab"
				role="tab"
				id="tab-{tab.id}"
				data-testid="tab-{tab.id}"
				aria-controls="tab-panel"
				aria-selected={tab.id === selectedTab ? 'true' : 'false'}
				tabindex={tab.id === selectedTab ? 0 : -1}
				onclick={() => (selectedTab = tab.id)}
				onkeydown={(event) => onTabKeydown(event, i)}>{tab.label}</button
			>
		{/each}
	</div>
	<div
		class="tabpanel"
		role="tabpanel"
		id="tab-panel"
		data-testid="tab-panel"
		aria-labelledby="tab-{selected.id}"
		tabindex="0">{selected.content}</div
	>
</div>

<section class="filter">
	<div class="field">
		<label class="field-label" for="filter-input">Filter items</label>
		<input
			class="input"
			id="filter-input"
			type="search"
			data-testid="filter-input"
			autocomplete="off"
			bind:value={query}
		/>
	</div>
	<p class="muted" data-testid="filter-count">{filterCountText(matches.length)}</p>
	{#if matches.length > 0}
		<ul class="list" data-testid="filter-list">
			{#each matches as item (item)}
				<li data-testid="filter-item">{item}</li>
			{/each}
		</ul>
	{:else}
		<p class="muted" data-testid="filter-empty">No matching items</p>
	{/if}
</section>
