// demos/interaction-benchmark/apps/react-router/app/routes/records.tsx
import { memo, useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import {
  RECORDS,
  ROUTES,
  documentTitle,
  formatUpdatedAt,
  nextSort,
  normalizeEditedName,
  recordsCountText,
  selectionSummaryText,
  visibleRecords,
  type BenchmarkRecord,
  type SortKey,
  type SortState,
} from "../shared/data";

export function meta() {
  return [{ title: documentTitle(ROUTES[1]!) }];
}

const RecordRow = memo(function RecordRow({
  record,
  checked,
  onToggle,
  onEdit,
}: {
  record: BenchmarkRecord;
  checked: boolean;
  onToggle: (id: string) => void;
  onEdit: (id: string, trigger: HTMLButtonElement) => void;
}) {
  return (
    <tr data-testid="record-row" data-id={record.id}>
      <td>
        <input
          type="checkbox"
          data-testid="record-select"
          aria-label={`Select ${record.name}`}
          checked={checked}
          onChange={() => onToggle(record.id)}
        />
      </td>
      <td data-testid="record-name">{record.name}</td>
      <td data-testid="record-email">{record.email}</td>
      <td data-testid="record-team">{record.team}</td>
      <td data-testid="record-score">{record.score}</td>
      <td data-testid="record-updated">{formatUpdatedAt(record.updatedAt)}</td>
      <td>
        <button
          type="button"
          className="button"
          data-testid="record-edit"
          aria-label={`Edit ${record.name}`}
          onClick={(event) => onEdit(record.id, event.currentTarget)}
        >
          Edit
        </button>
      </td>
    </tr>
  );
});

function EditDialog({
  record,
  onSave,
  onClose,
}: {
  record: BenchmarkRecord;
  onSave: (name: string) => void;
  onClose: () => void;
}) {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const [name, setName] = useState(record.name);
  const normalized = normalizeEditedName(name);

  useEffect(() => {
    dialogRef.current?.showModal();
    inputRef.current?.focus();
  }, []);

  function submit(event: FormEvent) {
    event.preventDefault();
    if (normalized === "") return;
    onSave(normalized);
    dialogRef.current?.close();
  }

  return (
    <dialog
      ref={dialogRef}
      className="dialog"
      data-testid="edit-dialog"
      aria-labelledby="edit-dialog-title"
      onClose={onClose}
    >
      <form onSubmit={submit}>
        <h2 className="dialog-title" id="edit-dialog-title" data-testid="edit-dialog-title">
          Edit record
        </h2>
        <div className="field">
          <label className="field-label" htmlFor="edit-name">
            Name
          </label>
          <input
            ref={inputRef}
            className="input"
            id="edit-name"
            data-testid="edit-name"
            value={name}
            onChange={(event) => setName(event.currentTarget.value)}
          />
        </div>
        <div className="dialog-actions">
          <button
            type="button"
            className="button"
            data-testid="edit-cancel"
            onClick={() => dialogRef.current?.close()}
          >
            Cancel
          </button>
          <button
            type="submit"
            className="button button-primary"
            data-testid="edit-save"
            disabled={normalized === ""}
          >
            Save
          </button>
        </div>
      </form>
    </dialog>
  );
}

export default function Records() {
  const [records, setRecords] = useState<readonly BenchmarkRecord[]>(RECORDS);
  const [query, setQuery] = useState("");
  const [sort, setSort] = useState<SortState | null>(null);
  const [selected, setSelected] = useState<ReadonlySet<string>>(() => new Set());
  const [editingId, setEditingId] = useState<string | null>(null);
  const triggerRef = useRef<HTMLButtonElement | null>(null);

  const rows = useMemo(() => visibleRecords(records, query, sort), [records, query, sort]);
  const editing = editingId === null ? null : records.find((r) => r.id === editingId) ?? null;

  const toggle = useCallback((id: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  const edit = useCallback((id: string, trigger: HTMLButtonElement) => {
    triggerRef.current = trigger;
    setEditingId(id);
  }, []);

  useEffect(() => {
    if (editingId === null && triggerRef.current) {
      triggerRef.current.focus();
      triggerRef.current = null;
    }
  }, [editingId]);

  function save(name: string) {
    const id = editingId;
    setRecords((prev) => prev.map((r) => (r.id === id ? { ...r, name } : r)));
  }

  function ariaSort(key: SortKey) {
    return sort?.key === key ? sort.direction : "none";
  }

  return (
    <>
      <h1 className="page-title" data-testid="page-title">
        Records
      </h1>
      <div className="records-toolbar">
        <div className="field">
          <label className="field-label" htmlFor="records-search">
            Search records
          </label>
          <input
            className="input"
            id="records-search"
            type="search"
            data-testid="records-search"
            value={query}
            onChange={(event) => setQuery(event.currentTarget.value)}
          />
        </div>
        <p className="muted" data-testid="records-count">
          {recordsCountText(rows.length, records.length)}
        </p>
        <p className="summary" data-testid="selection-summary" role="status">
          {selectionSummaryText(selected.size)}
        </p>
      </div>
      <table className="records-table" data-testid="records-table">
        <thead>
          <tr>
            <th aria-label="Select" />
            <th aria-sort={ariaSort("name")}>
              <button
                type="button"
                className="sort-button"
                data-testid="sort-name"
                onClick={() => setSort((s) => nextSort(s, "name"))}
              >
                Name
              </button>
            </th>
            <th>Email</th>
            <th>Team</th>
            <th aria-sort={ariaSort("score")}>
              <button
                type="button"
                className="sort-button"
                data-testid="sort-score"
                onClick={() => setSort((s) => nextSort(s, "score"))}
              >
                Score
              </button>
            </th>
            <th>Updated</th>
            <th aria-label="Actions" />
          </tr>
        </thead>
        <tbody>
          {rows.length === 0 ? (
            <tr>
              <td colSpan={7} data-testid="records-empty">
                No records match
              </td>
            </tr>
          ) : (
            rows.map((record) => (
              <RecordRow
                key={record.id}
                record={record}
                checked={selected.has(record.id)}
                onToggle={toggle}
                onEdit={edit}
              />
            ))
          )}
        </tbody>
      </table>
      {editing && (
        <EditDialog
          key={editing.id}
          record={editing}
          onSave={save}
          onClose={() => setEditingId(null)}
        />
      )}
    </>
  );
}

// demos/interaction-benchmark/apps/solidstart/src/routes/records.tsx
import { Title } from "@solidjs/meta";
import { createMemo, createSignal, createStore, flush, For, onSettled, Show, untrack } from "solid-js";
import {
  type BenchmarkRecord,
  documentTitle,
  formatUpdatedAt,
  nextSort,
  normalizeEditedName,
  RECORDS,
  recordsCountText,
  ROUTES,
  selectionSummaryText,
  type SortKey,
  type SortState,
  visibleRecords,
} from "../shared/data";

interface Editing {
  record: BenchmarkRecord;
  trigger: HTMLButtonElement;
}

export default function Records() {
  const [records, setRecords] = createStore<BenchmarkRecord[]>(RECORDS.map((record) => ({ ...record })));
  const [selected, setSelected] = createStore<Record<string, boolean>>({});
  const [query, setQuery] = createSignal("");
  const [sort, setSort] = createSignal<SortState | null>(null);
  const [editing, setEditing] = createSignal<Editing | null>(null);

  const visible = createMemo(() => visibleRecords(records, query(), sort()));
  const selectedCount = createMemo(() => records.filter((record) => selected[record.id]).length);
  const ariaSort = (key: SortKey) => {
    const current = sort();
    return current?.key === key ? current.direction : "none";
  };

  const closeDialog = (name?: string) => {
    const current = editing();
    if (!current) return;
    if (name !== undefined) {
      const id = current.record.id;
      setRecords((draft) => {
        const record = draft.find((item) => item.id === id);
        if (record) record.name = name;
      });
    }
    setEditing(null);
    // The modal must leave the DOM before focus can return to a control behind it.
    flush();
    current.trigger.focus();
  };

  return (
    <>
      <Title>{documentTitle(ROUTES[1]!)}</Title>
      <h1 class="page-title" data-testid="page-title">Records</h1>
      <div class="records-toolbar">
        <div class="field">
          <label class="field-label" for="records-search">Search records</label>
          <input
            id="records-search"
            class="input"
            type="search"
            data-testid="records-search"
            value={query()}
            onInput={(event) => setQuery(event.currentTarget.value)}
          />
        </div>
        <p class="muted" data-testid="records-count">{recordsCountText(visible().length, records.length)}</p>
        <p class="summary" data-testid="selection-summary" role="status">{selectionSummaryText(selectedCount())}</p>
      </div>
      <table class="records-table" data-testid="records-table">
        <thead>
          <tr>
            <th aria-label="Select" />
            <th aria-sort={ariaSort("name")}>
              <button type="button" class="sort-button" data-testid="sort-name" onClick={() => setSort((s) => nextSort(s, "name"))}>
                Name
              </button>
            </th>
            <th>Email</th>
            <th>Team</th>
            <th aria-sort={ariaSort("score")}>
              <button type="button" class="sort-button" data-testid="sort-score" onClick={() => setSort((s) => nextSort(s, "score"))}>
                Score
              </button>
            </th>
            <th>Updated</th>
            <th aria-label="Actions" />
          </tr>
        </thead>
        <tbody>
          <For
            each={visible()}
            fallback={
              <tr>
                <td colspan="7" data-testid="records-empty">No records match</td>
              </tr>
            }
          >
            {(record) => (
              <tr data-testid="record-row" data-id={record.id}>
                <td>
                  <input
                    type="checkbox"
                    data-testid="record-select"
                    aria-label={`Select ${record.name}`}
                    checked={selected[record.id] === true}
                    onChange={(event) => {
                      const checked = event.currentTarget.checked;
                      setSelected((draft) => {
                        draft[record.id] = checked;
                      });
                    }}
                  />
                </td>
                <td data-testid="record-name">{record.name}</td>
                <td data-testid="record-email">{record.email}</td>
                <td data-testid="record-team">{record.team}</td>
                <td data-testid="record-score">{record.score}</td>
                <td data-testid="record-updated">{formatUpdatedAt(record.updatedAt)}</td>
                <td>
                  <button
                    type="button"
                    class="button"
                    data-testid="record-edit"
                    aria-label={`Edit ${record.name}`}
                    onClick={(event) => setEditing({ record, trigger: event.currentTarget })}
                  >
                    Edit
                  </button>
                </td>
              </tr>
            )}
          </For>
        </tbody>
      </table>
      <Show when={editing()} keyed>
        {(current) => <EditDialog initialName={current.record.name} onClose={closeDialog} />}
      </Show>
    </>
  );
}

function EditDialog(props: { initialName: string; onClose: (name?: string) => void }) {
  const [name, setName] = createSignal(untrack(() => props.initialName));
  let dialog!: HTMLDialogElement;
  let input!: HTMLInputElement;

  onSettled(() => {
    dialog.showModal();
    input.focus();
  });

  return (
    <dialog
      ref={(el) => (dialog = el)}
      class="dialog"
      data-testid="edit-dialog"
      aria-labelledby="edit-dialog-title"
      onCancel={(event) => {
        event.preventDefault();
        props.onClose();
      }}
    >
      <form
        onSubmit={(event) => {
          event.preventDefault();
          const value = normalizeEditedName(name());
          if (value !== "") props.onClose(value);
        }}
      >
        <h2 class="dialog-title" id="edit-dialog-title" data-testid="edit-dialog-title">Edit record</h2>
        <div class="field">
          <label class="field-label" for="edit-name">Name</label>
          <input
            ref={(el) => (input = el)}
            id="edit-name"
            class="input"
            data-testid="edit-name"
            value={name()}
            onInput={(event) => setName(event.currentTarget.value)}
          />
        </div>
        <div class="dialog-actions">
          <button type="button" class="button" data-testid="edit-cancel" onClick={() => props.onClose()}>
            Cancel
          </button>
          <button
            type="submit"
            class="button button-primary"
            data-testid="edit-save"
            disabled={normalizeEditedName(name()) === ""}
          >
            Save
          </button>
        </div>
      </form>
    </dialog>
  );
}
